services:
  microservicio:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@n72bzhzwyzgte7oh_tp?TNS_ADMIN=/app/oracle_wallet
      - spring.datasource.username=MIGUEL
      - spring.datasource.password=ClaseBD123456-
